apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketACL
metadata:
 name: crossplane-bucket-acl
spec:
 forProvider:
  acl: private
  bucketSelector:
   matchLabels:
    testing.crossplane.io/scenario: changelogs-bucket
  region: us-west-1