apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  generateName: crossplane-bucket-
  labels:
    testing.crossplane.io/scenario: changelogs-bucket
spec:
  forProvider:
    region: us-west-1